app = "rag-ai-agent-backend"
primary_region = "sjc"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8000"

[env.secrets]
  GROQ_API_KEY = ""
  PINECONE_API_KEY = ""
  TAVILY_API_KEY = ""
  JINA_API_KEY = ""

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
